version: "3.8"
services:
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile.proxy
    ports:
      - 127.0.0.1:80:80
    depends_on:
      - redis
    networks:
      main:
        aliases:
          - proxy
  redis:
    image: redis:latest
    command: redis-server --requirepass 206a7857-3963-4359-aa95-c10a2c716148
    ports:
      - 6379:6379
    networks:
      main:
        aliases:
          - redis
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    depends_on:
      - redis
    command: node --trace-warnings dist/index.js
    networks:
      main:
        aliases:
          - server
    restart: always
networks:
  main: